### ISSUE TITLE
is there a way to render content inside the HEAD of the template?

### ISSUE THREAD

**Issue by badpenguin** [GoogleChromeLabs/prerender-loader#26]
I was able to configure webpack to render multiple pages.

I just miss the chance to dynamically modify the HEAD tag to add, via React, the title, SEO tags and maybe additional custom tags like canonical and other stuffs (preload, fonts, etc.).

I don't want to do it manually in every html page but i wish to pre-render them as well.

Is there a way to accomplish this?

**Comment by developit** [comment]
Use react-helmet or similar:

```js
// in your app.js (or whatever)
import React from 'react';
import { Helmet } from 'react-helmet';

export default class App extends React.Component {
  render () {
    return (
        <div className="app">
            <Helmet>
                <meta charset="utf8" />
                <title>My App's Title</title>
                <link rel="canonical" href="http://mysite.com/example" />
            </Helmet>
            ... etc
        </div>
    );
  }
};
```

```js
// file: prerender.js
import { renderToString } from 'react-dom/server';
import React from 'react';
import { Helmet } from 'react-helmet';
import App from './app';

export default function(data) {
  // render the app:
  const body = renderToString(<App {...data} />);

  // grab all the head stuff:
  const helmet = Helmet.renderStatic();

  // construct the document using both:
  const html = `
    <!doctype html>
    <html ${helmet.htmlAttributes.toString()}>
        <head>
            ${helmet.title.toString()}
            ${helmet.meta.toString()}
            ${helmet.link.toString()}
        </head>
        <body ${helmet.bodyAttributes.toString()}>
            <div id="approot">
                ${body}
            </div>
        </body>
    </html>
  `;

  return html;
}
```

```js
// in your webpack.config.js:

plugins: [
  new HtmlWebpackPlugin({
    template: 'prerender-loader?string!./prerender.js'
  })
]
```


For preloading fonts I'd recommend using a less direct solution than injecting them into the head. Perhaps [critters](https://github.com/googlechromelabs/critters].

**Comment by badpenguin** [comment]
Thanks!

**Comment by ernie-h** [comment]
Sorry to bring this up after so long @developit, but I found this thread very helpful. I had a question regarding where your client side rendering file is in all this (i.e `index.js`). Where do you actually call `ReactDOM.render(<App />, document.getElementById("approot"))`? I'm getting an error in my entry file for webpack where I call :
```
export default () => {
  ReactDOM.render(<App />, document.getElementById('approot'));
};

``` 
Error is :
`Error: Target container is not a DOM element.`

FYI I'm also using `pre-render` loader for Webpack

**Comment by developit** [comment]
@ernie-h the most common approach is to conditionally call render:

```
if (typeof document !== 'undefined') {
  ReactDOM.render(<App />, document.getElementById('approot'));
}
```
