### ISSUE TITLE
Error: Conflict: Multiple chunks emit assets to the same filename ssr-bundle.js

### ISSUE THREAD

**Issue by edwardfhsiao** [GoogleChromeLabs/prerender-loader#29]
Hi, I have encountered this problem when I was trying to create multiple html files with multiple entries.
```shell
Error: Child compilation failed:
  Error: Conflict: Multiple chunks emit assets to the same filename ssr-bundle.js (chunks 1 and 2  )
```

```js
//webpack config
config.entry = {
  a: './a.js',
  b: './b.js',
}

Object.keys(config.entry).map(i => {
  config.plugins.push(
    new HtmlWebpackPlugin({
      template: `!!prerender-loader?string!./template.html`,
      filename: `${i}.html`,
      hash: false,
      chunks: [i],
    }),
  );
});
```

I have tried below but doesnt make any difference.
 ```js
template: `!!prerender-loader?${JSON.stringify({ string: true, params: { url: `/${i}/` } })}!./template.html`
```

```js
        "html-webpack-plugin": "^4.0.0-alpha.2",
        "prerender-loader": "^1.2.0",
        "webpack": "^4.29.3",
        "webpack-assets-manifest": "^2.0.0",
        "webpack-cli": "^3.1.1",
        "webpack-dev-server": "^3.1.14"
```
node v11.9.0.

Any ideas?

**Comment by edwardfhsiao** [comment]
testing repo https://github.com/edwardfhsiao/prerender-loader-test-repo
```sh
$ npm i
$ npm run compile
```

**Comment by developit** [comment]
I'm wondering if removing the cache inheritance would fix this:
https://github.com/GoogleChromeLabs/prerender-loader/blob/master/src/index.js#L131-L143

**Comment by developit** [comment]
I think I found the issue, I was using `os.tmpdir()`, but had meant to use `fs.mkdtempSync()`.

**Comment by developit** [comment]
@edwardfhsiao alright, I figured out the issue with the demo you linked above:  it's a duplicate of #25, and the [solution I posted there](https://github.com/GoogleChromeLabs/prerender-loader/issues/25#issuecomment-466397030) a couple hours ago works here too:

```diff
Object.keys(config.entry).map(i => {
  config.plugins.push(
    new HtmlWebpackPlugin({
-     template: `!!prerender-loader?string!${PATH.HTML_PATH}/template.html`,
+     template: `!!prerender-loader?string&entry=${config.entry[i]}!${PATH.HTML_PATH}/template.html`,
      // etc
    }),
  );
});
```

**Comment by edwardfhsiao** [comment]
Awesome, that solved my problem. Really appreciated your help!

**Comment by northamerican** [comment]
@edwardfhsiao  @developit 

This issue may have to be looked at again. The error still occurs if using the `{{prerender}}` in the template tag as specified in the docs:
https://github.com/GoogleChromeLabs/prerender-loader#injecting-content-into-the-html

I spent many hours trying to debug our config and was still getting the multiple chunks error until i realized this.

To replicate, replace the template.html file in the example repo (https://github.com/edwardfhsiao/prerender-loader-test-repo) with:
```
<div id="root">{{prerender}}</div>
```
and run `npm run compile` or `yarn compile`.

It's not clear where the `<%= htmlWebpackPlugin.options.title %>` formatting comes from, but using `{{prerender}}` in the template as specified in the docs fails with multiple entry files.

I can open a new issue if needed.

**Comment by edwardfhsiao** [comment]
@northamerican ```<%= htmlWebpackPlugin.options.title %>```just comes from 
```js
 new HtmlWebpackPlugin({
      ...
      title: `${i}`,
```
It is a format of HtmlWebpackPlugin, which does not really matter in this case.

As for the multiple entry issues, I guess still need @developit 's help.
