### ISSUE TITLE
It's work in Angular eject?

### ISSUE THREAD

**Issue by splincode** [GoogleChromeLabs/prerender-loader#4]
If we usage for Angular, that be worked?

**Comment by developit** [comment]
I'm not quite familiar enough with angular-cli's Eject feature to know. Hopefully someone else is and can shed some light!

**Comment by mattdsteele** [comment]
Just gave this a shot (with `@angular/cli@1.7.4`, as the latest CLI doesn't support eject), and ran into this issue, as there are multiple entries: https://github.com/GoogleChromeLabs/prerender-loader/issues/3

**Comment by developit** [comment]
Multiple Entries support has been added in [1.1.0](https://github.com/GoogleChromeLabs/prerender-loader/releases/tag/1.1.0).
